src/Entity/Advert.php
<?php

namespace App\Entity;

use App\Repository\AdvertRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Table(name="advert")
 * @ORM\Entity(repositoryClass=AdvertRepository::class)
 */
class Advert
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(name="id", type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank
     * @Assert\Length(max = 255)
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $Title;

    /**
     * @Assert\NotBlank
     *
     * @ORM\Column(name="content", type="text")
     */
    private $Content;

    /**
     * @Assert\NotBlank
     * @Assert\Positive
     *
     * @ORM\Column(name="price", type="float")
     */
    private $Price;

    /**
     * @Assert\NotBlank
     * @Assert\Length(max = 6)
     * @Assert\Positive
     *
     * @ORM\Column(name="postal_code", type="string", length=6)
     */
    private $PostalCode;

    /**
     * @ORM\Column(name="creation_date", type="datetime")
     */
    private $CreationDate;

    /**
     * @Assert\NotBlank
     * @Assert\Url
     *
     * @ORM\Column(name="photo1", type="text", nullable=true)
     */
    private $Photo1;

    /**
     * @ORM\Column(name="photo2", type="text", nullable=true)
     */
    private $Photo2;

    /**
     * @ORM\Column(name="photo3", type="text", nullable=true)
     */
    private $Photo3;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="adverts")
     * @ORM\JoinColumn(name="category_id", referencedColumnName="id")
     */
    private $Category;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(float $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->PostalCode;
    }

    public function setPostalCode(string $PostalCode): self
    {
        $this->PostalCode = $PostalCode;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->CreationDate;
    }

    public function setCreationDate(\DateTimeInterface $CreationDate): self
    {
        $this->CreationDate = $CreationDate;

        return $this;
    }

    public function getPhoto1(): ?string
    {
        return $this->Photo1;
    }

    public function setPhoto1(?string $Photo1): self
    {
        $this->Photo1 = $Photo1;

        return $this;
    }

    public function getPhoto2(): ?string
    {
        return $this->Photo2;
    }

    public function setPhoto2(?string $Photo2): self
    {
        $this->Photo2 = $Photo2;

        return $this;
    }

    public function getPhoto3(): ?string
    {
        return $this->Photo3;
    }

    public function setPhoto3(?string $Photo3): self
    {
        $this->Photo3 = $Photo3;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): self
    {
        $this->Category = $Category;

        return $this;
    }
}

src/Form/AdvertType.php
<?php


namespace App\Form;


use App\Entity\Advert;
use App\Entity\Category;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdvertType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class)
            ->add('content', TextareaType::class)
            ->add('price', MoneyType::class)
            ->add('postal_code', TextType::class)
            ->add('photo1', UrlType::class)
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'name',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Advert::class,
        ]);
    }
}

src/Controller/AdvertController.php
<?php

namespace App\Controller;

use App\Entity\Advert;
use App\Form\AdvertType;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AdvertController extends AbstractController
{
    /**
     * @Route("/annonces.html", name="app.advert_all")
     */
    public function showAllAction()
    {
        $advertArray = $this->getDoctrine()
            ->getRepository(Advert::class)
            ->findAllJoinToCategory();

        return $this->render('advert/advert.html.twig', [
            'advertArray' => $advertArray,
        ]);
    }

    /**
     * @Route("/nouvelle-annonce.html", name="app.advert_create", methods={"GET", "POST"})
     */
    public function newAction(Request $request)
    {
        return $this->processsForm($request, new Advert());
    }

    /**
     * @param Request $request
     * @param Advert $advert
     *
     * @return RedirectResponse|Response
     */
    private function processsForm(Request $request, Advert $advert)
    {
        $form = $this->createForm(AdvertType::class, $advert);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $advert = $form->getData();
            $advert->setCreationDate(new \DateTime());

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($advert);
            $entityManager->flush();

            return $this->redirect($this->generateUrl('app.advert_all'));
        }

        return $this->render('advert/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/advert/advert.html.twig
{% extends "base.html.twig" %}

{% block title %}Toutes les annonces{% endblock %}
{% block meta_desc %}Retrouvez sur cette page toutes les annonces du site Les Petites Annonces.{% endblock %}

{% block body %}
    <main>
        <div class="container">
            <h1>Toutes les annonces :</h1>

            <div class="row">
                {% for advert in advertArray %}
                    <div class="col-md-6 mb-3">
                        <div class="card h-100">
                            <div class="row no-gutters h-100">
                                <div class="col-md-4">
                                    <img src="{{ advert.photo1 }}" class="card-img h-100" alt="Photo fictive de l'annonce" style="object-fit: cover">
                                </div>
                                <div class="col-md-8">
                                    <div class="card-body">
                                        <h2 class="card-title"><span style="color: {{ advert.category.color }}">{{ advert.category.name }}</span> : {{ advert.title }}</h2>
                                        <p class="card-subtitle mb-2 text-muted">{{ advert.price|format_currency('EUR') }}</p>
                                        <p class="card-text">{{ advert.content|slice(0, 75) }}...</p>
                                        <p class="card-text"><small class="text-muted">Code postale : {{ advert.postalCode|number_format(0, '.', ' ') }}</small></p>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted">Posté le {{ advert.creationDate|date("d-m-Y à H:m") }}</small>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </main>
{% endblock %}

templates/advert/new.html.twig
{% extends "base.html.twig" %}

{% block title %}Ajouter une annonce{% endblock %}
{% block meta_desc %}Cette page permet d'ajouter une annonce.{% endblock %}

{% block body %}
    <main>
        <div class="container">
            <h1>Ajouter une annonce :</h1>

            <form action="{{ path('app.advert_create') }}" method="post">
                {{ form_widget(form) }}
                <input type="submit">
            </form>
        </div>
    </main>
{% endblock %}